# Je pars d'une image de base Python 3.13.3 sur Alpine
FROM python:3.13.3-alpine 

# Je crée mon répertoire de travail
WORKDIR /code 

# J'installe mes requirements
COPY ./requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Je lance mon code
COPY discord_moderation.py .
CMD ["python", "discord_moderation.py"]